#!/usr/bin/env python3
"""Document / bootstrap Alembic usage for NeoBusiness AI.

Prefer the checked-in tree:
  - backend/alembic.ini
  - backend/alembic/env.py  (imports Base from database.py)
  - backend/alembic/versions/001_initial_stub.py

Examples (run from backend/ with venv active and DATABASE_URL set):

  # Apply migrations
  alembic upgrade head

  # Generate a new revision from model diffs
  alembic revision --autogenerate -m "add_foo_column"

  # Always review autogenerated files before upgrade — models in
  # database.py are large; first real sync may be noisy.

Docker:
  docker compose exec api alembic upgrade head
"""

from __future__ import annotations


def main() -> None:
    print(__doc__)


if __name__ == "__main__":
    main()
